package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Audiorecords generated by hbm2java
 */
@Entity
@Table(name="audiorecords"
    ,catalog="sos112"
)
public class Audiorecords  implements java.io.Serializable {


     private String timeDate;
     private String postId;
     private byte[] audioFile;
     private String fileUrl;

    public Audiorecords() {
    }

    public Audiorecords(String timeDate, String postId, byte[] audioFile, String fileUrl) {
       this.timeDate = timeDate;
       this.postId = postId;
       this.audioFile = audioFile;
       this.fileUrl = fileUrl;
    }
   
     @Id 

    
    @Column(name="timeDate", nullable=false)
    public String getTimeDate() {
        return this.timeDate;
    }
    
    public void setTimeDate(String timeDate) {
        this.timeDate = timeDate;
    }

    
    @Column(name="postId", nullable=false)
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }

    
    @Column(name="audioFile", nullable=false)
    public byte[] getAudioFile() {
        return this.audioFile;
    }
    
    public void setAudioFile(byte[] audioFile) {
        this.audioFile = audioFile;
    }

    
    @Column(name="fileUrl", nullable=false, length=500)
    public String getFileUrl() {
        return this.fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }




}


