package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Callrecords generated by hbm2java
 */
@Entity
@Table(name="callrecords"
    ,catalog="sos112"
)
public class Callrecords  implements java.io.Serializable {


     private String callTime;
     private String postId;
     private String number;
     private String status;

    public Callrecords() {
    }

    public Callrecords(String callTime, String postId, String number, String status) {
       this.callTime = callTime;
       this.postId = postId;
       this.number = number;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="callTime", nullable=false)
    public String getCallTime() {
        return this.callTime;
    }
    
    public void setCallTime(String callTime) {
        this.callTime = callTime;
    }

    
    @Column(name="postId", nullable=false)
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }

    
    @Column(name="number", nullable=false)
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }

    
    @Column(name="status", nullable=false)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


