package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ContinuousLocation generated by hbm2java
 */
@Entity
@Table(name="continuous_location"
    ,catalog="sos112"
)
public class ContinuousLocation  implements java.io.Serializable {


     private String id;
     private String userId;
     private double latitude;
     private double longitude;
     private String date;

    public ContinuousLocation() {
    }

    public ContinuousLocation(String id, String userId, double latitude, double longitude, String date) {
       this.id = id;
       this.userId = userId;
       this.latitude = latitude;
       this.longitude = longitude;
       this.date = date;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="latitude", nullable=false, precision=22, scale=0)
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", nullable=false, precision=22, scale=0)
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="date", nullable=false)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


