package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countsospostuserview generated by hbm2java
 */
@Entity
@Table(name="countsospostuserview"
    ,catalog="sos112"
)
public class Countsospostuserview  implements java.io.Serializable {


     private String userView;
     private String timeDate;
     private String sosPostId;
     private String userId;

    public Countsospostuserview() {
    }

    public Countsospostuserview(String userView, String timeDate, String sosPostId, String userId) {
       this.userView = userView;
       this.timeDate = timeDate;
       this.sosPostId = sosPostId;
       this.userId = userId;
    }
   
     @Id 

    
    @Column(name="userView", nullable=false)
    public String getUserView() {
        return this.userView;
    }
    
    public void setUserView(String userView) {
        this.userView = userView;
    }

    
    @Column(name="time_Date", nullable=false)
    public String getTimeDate() {
        return this.timeDate;
    }
    
    public void setTimeDate(String timeDate) {
        this.timeDate = timeDate;
    }

    
    @Column(name="sosPostId", nullable=false)
    public String getSosPostId() {
        return this.sosPostId;
    }
    
    public void setSosPostId(String sosPostId) {
        this.sosPostId = sosPostId;
    }

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }




}


