package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Editimagefour generated by hbm2java
 */
@Entity
@Table(name="editimagefour"
    ,catalog="sos112"
)
public class Editimagefour  implements java.io.Serializable {


     private String postId;
     private byte[] file;
     private String fileUrl;

    public Editimagefour() {
    }

    public Editimagefour(String postId, byte[] file, String fileUrl) {
       this.postId = postId;
       this.file = file;
       this.fileUrl = fileUrl;
    }
   
     @Id 

    
    @Column(name="postId", nullable=false)
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }

    
    @Column(name="file", nullable=false)
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }

    
    @Column(name="fileUrl", nullable=false, length=500)
    public String getFileUrl() {
        return this.fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }




}


