package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Extraimageone generated by hbm2java
 */
@Entity
@Table(name="extraimageone"
    ,catalog="sos112"
)
public class Extraimageone  implements java.io.Serializable {


     private String postId;
     private byte[] imageOne;
     private String fileUrl;

    public Extraimageone() {
    }

    public Extraimageone(String postId, byte[] imageOne, String fileUrl) {
       this.postId = postId;
       this.imageOne = imageOne;
       this.fileUrl = fileUrl;
    }
   
     @Id 

    
    @Column(name="postId", nullable=false)
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }

    
    @Column(name="imageOne", nullable=false)
    public byte[] getImageOne() {
        return this.imageOne;
    }
    
    public void setImageOne(byte[] imageOne) {
        this.imageOne = imageOne;
    }

    
    @Column(name="fileUrl", nullable=false, length=500)
    public String getFileUrl() {
        return this.fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }




}


