package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name="feedback"
    ,catalog="sos112"
)
public class Feedback  implements java.io.Serializable {


     private String userId;
     private String rate;
     private String type;
     private String details;

    public Feedback() {
    }

    public Feedback(String userId, String rate, String type, String details) {
       this.userId = userId;
       this.rate = rate;
       this.type = type;
       this.details = details;
    }
   
     @Id 

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="rate", nullable=false)
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }

    
    @Column(name="type", nullable=false)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="details", nullable=false, length=1000)
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }




}


