package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gcmid generated by hbm2java
 */
@Entity
@Table(name="gcmid"
    ,catalog="sos112"
)
public class Gcmid  implements java.io.Serializable {


     private String id;
     private String gcm;

    public Gcmid() {
    }

    public Gcmid(String id, String gcm) {
       this.id = id;
       this.gcm = gcm;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="gcm", nullable=false)
    public String getGcm() {
        return this.gcm;
    }
    
    public void setGcm(String gcm) {
        this.gcm = gcm;
    }




}


