package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GeolocationConvertAddress generated by hbm2java
 */
@Entity
@Table(name="geolocation_convert_address"
    ,catalog="sos112"
)
public class GeolocationConvertAddress  implements java.io.Serializable {


     private String userId;
     private String addressOne;
     private String date;
     private String time;

    public GeolocationConvertAddress() {
    }

    public GeolocationConvertAddress(String userId, String addressOne, String date, String time) {
       this.userId = userId;
       this.addressOne = addressOne;
       this.date = date;
       this.time = time;
    }
   
     @Id 

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="addressOne", nullable=false)
    public String getAddressOne() {
        return this.addressOne;
    }
    
    public void setAddressOne(String addressOne) {
        this.addressOne = addressOne;
    }

    
    @Column(name="date", nullable=false)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    
    @Column(name="time", nullable=false)
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }




}


