package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GroupHasUser generated by hbm2java
 */
@Entity
@Table(name="group_has_user"
    ,catalog="sos112"
)
public class GroupHasUser  implements java.io.Serializable {


     private String id;
     private String groupid;
     private String userid;

    public GroupHasUser() {
    }

	
    public GroupHasUser(String id) {
        this.id = id;
    }
    public GroupHasUser(String id, String groupid, String userid) {
       this.id = id;
       this.groupid = groupid;
       this.userid = userid;
    }
   
     @Id 

    
    @Column(name="ID", nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="GROUPID")
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    
    @Column(name="USERID")
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }




}


