package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Imeinumber generated by hbm2java
 */
@Entity
@Table(name="imeinumber"
    ,catalog="sos112"
)
public class Imeinumber  implements java.io.Serializable {


     private String dateTime;
     private String userId;
     private String imeiNumber;

    public Imeinumber() {
    }

    public Imeinumber(String dateTime, String userId, String imeiNumber) {
       this.dateTime = dateTime;
       this.userId = userId;
       this.imeiNumber = imeiNumber;
    }
   
     @Id 

    
    @Column(name="dateTime", nullable=false)
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="imeiNumber", nullable=false)
    public String getImeiNumber() {
        return this.imeiNumber;
    }
    
    public void setImeiNumber(String imeiNumber) {
        this.imeiNumber = imeiNumber;
    }




}


