package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Otpcode generated by hbm2java
 */
@Entity
@Table(name="otpcode"
    ,catalog="sos112"
)
public class Otpcode  implements java.io.Serializable {


     private String userId;
     private String mobileNumber;
     private String code;

    public Otpcode() {
    }

    public Otpcode(String userId, String mobileNumber, String code) {
       this.userId = userId;
       this.mobileNumber = mobileNumber;
       this.code = code;
    }
   
     @Id 

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="mobileNumber", nullable=false)
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    
    @Column(name="code", nullable=false)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }




}


