package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profilepicture generated by hbm2java
 */
@Entity
@Table(name="profilepicture"
    ,catalog="sos112"
)
public class Profilepicture  implements java.io.Serializable {


     private String userId;
     private byte[] picture;
     private String fileUrl;

    public Profilepicture() {
    }

    public Profilepicture(String userId, byte[] picture, String fileUrl) {
       this.userId = userId;
       this.picture = picture;
       this.fileUrl = fileUrl;
    }
   
     @Id 

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="picture", nullable=false)
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    
    @Column(name="fileUrl", nullable=false, length=500)
    public String getFileUrl() {
        return this.fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }




}


