package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sensetstatus generated by hbm2java
 */
@Entity
@Table(name="sensetstatus"
    ,catalog="sos112"
)
public class Sensetstatus  implements java.io.Serializable {


     private String userId;
     private String video;
     private String sms;
     private String sosIcon;
     private String powerButton;
     private String fallSenser;
     private String shakeToPost;

    public Sensetstatus() {
    }

	
    public Sensetstatus(String userId, String video, String sms, String sosIcon, String powerButton) {
        this.userId = userId;
        this.video = video;
        this.sms = sms;
        this.sosIcon = sosIcon;
        this.powerButton = powerButton;
    }
    public Sensetstatus(String userId, String video, String sms, String sosIcon, String powerButton, String fallSenser, String shakeToPost) {
       this.userId = userId;
       this.video = video;
       this.sms = sms;
       this.sosIcon = sosIcon;
       this.powerButton = powerButton;
       this.fallSenser = fallSenser;
       this.shakeToPost = shakeToPost;
    }
   
     @Id 

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="video", nullable=false, length=10)
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }

    
    @Column(name="sms", nullable=false)
    public String getSms() {
        return this.sms;
    }
    
    public void setSms(String sms) {
        this.sms = sms;
    }

    
    @Column(name="sosIcon", nullable=false, length=10)
    public String getSosIcon() {
        return this.sosIcon;
    }
    
    public void setSosIcon(String sosIcon) {
        this.sosIcon = sosIcon;
    }

    
    @Column(name="powerButton", nullable=false, length=10)
    public String getPowerButton() {
        return this.powerButton;
    }
    
    public void setPowerButton(String powerButton) {
        this.powerButton = powerButton;
    }

    
    @Column(name="fallSenser", length=10)
    public String getFallSenser() {
        return this.fallSenser;
    }
    
    public void setFallSenser(String fallSenser) {
        this.fallSenser = fallSenser;
    }

    
    @Column(name="shakeToPost", length=10)
    public String getShakeToPost() {
        return this.shakeToPost;
    }
    
    public void setShakeToPost(String shakeToPost) {
        this.shakeToPost = shakeToPost;
    }




}


