package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sessionkey generated by hbm2java
 */
@Entity
@Table(name="sessionkey"
    ,catalog="sos112"
)
public class Sessionkey  implements java.io.Serializable {


     private String id;
     private String mobile;

    public Sessionkey() {
    }

    public Sessionkey(String id, String mobile) {
       this.id = id;
       this.mobile = mobile;
    }
   
     @Id 

    
    @Column(name="Id", nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="mobile", nullable=false)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }




}


