package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Soscontact generated by hbm2java
 */
@Entity
@Table(name="soscontact"
    ,catalog="sos112"
)
public class Soscontact  implements java.io.Serializable {


     private String userId;
     private String sosContactOne;
     private String sosContactTwo;
     private String sosContactThree;
     private String emergencyNumber;

    public Soscontact() {
    }

	
    public Soscontact(String userId, String sosContactOne, String sosContactTwo, String sosContactThree) {
        this.userId = userId;
        this.sosContactOne = sosContactOne;
        this.sosContactTwo = sosContactTwo;
        this.sosContactThree = sosContactThree;
    }
    public Soscontact(String userId, String sosContactOne, String sosContactTwo, String sosContactThree, String emergencyNumber) {
       this.userId = userId;
       this.sosContactOne = sosContactOne;
       this.sosContactTwo = sosContactTwo;
       this.sosContactThree = sosContactThree;
       this.emergencyNumber = emergencyNumber;
    }
   
     @Id 

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="sosContactOne", nullable=false)
    public String getSosContactOne() {
        return this.sosContactOne;
    }
    
    public void setSosContactOne(String sosContactOne) {
        this.sosContactOne = sosContactOne;
    }

    
    @Column(name="sosContactTwo", nullable=false)
    public String getSosContactTwo() {
        return this.sosContactTwo;
    }
    
    public void setSosContactTwo(String sosContactTwo) {
        this.sosContactTwo = sosContactTwo;
    }

    
    @Column(name="sosContactThree", nullable=false)
    public String getSosContactThree() {
        return this.sosContactThree;
    }
    
    public void setSosContactThree(String sosContactThree) {
        this.sosContactThree = sosContactThree;
    }

    
    @Column(name="emergencyNumber", length=50)
    public String getEmergencyNumber() {
        return this.emergencyNumber;
    }
    
    public void setEmergencyNumber(String emergencyNumber) {
        this.emergencyNumber = emergencyNumber;
    }




}


