package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sospostfinal generated by hbm2java
 */
@Entity
@Table(name="sospostfinal"
    ,catalog="sos112"
)
public class Sospostfinal  implements java.io.Serializable {


     private String id;
     private String postId;
     private String postTitle;
     private String helpType;
     private String dateTime;

    public Sospostfinal() {
    }

    public Sospostfinal(String id, String postId, String postTitle, String helpType, String dateTime) {
       this.id = id;
       this.postId = postId;
       this.postTitle = postTitle;
       this.helpType = helpType;
       this.dateTime = dateTime;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="postId", nullable=false)
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }

    
    @Column(name="postTitle", nullable=false)
    public String getPostTitle() {
        return this.postTitle;
    }
    
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }

    
    @Column(name="helpType", nullable=false)
    public String getHelpType() {
        return this.helpType;
    }
    
    public void setHelpType(String helpType) {
        this.helpType = helpType;
    }

    
    @Column(name="dateTime", nullable=false)
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }




}


