package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sospost generated by hbm2java
 */
@Entity
@Table(name="sospost"
    ,catalog="sos112"
)
public class Sospost  implements java.io.Serializable {


     private String postId;
     private String userId;
     private String userName;
     private String latitude;
     private String longitude;
     private String insertDate;
     private String insertTime;
     private String lastLatitude;
     private String lastLongitude;
     private String witness;
     private String helpType;

    public Sospost() {
    }

    public Sospost(String postId, String userId, String userName, String latitude, String longitude, String insertDate, String insertTime, String lastLatitude, String lastLongitude, String witness, String helpType) {
       this.postId = postId;
       this.userId = userId;
       this.userName = userName;
       this.latitude = latitude;
       this.longitude = longitude;
       this.insertDate = insertDate;
       this.insertTime = insertTime;
       this.lastLatitude = lastLatitude;
       this.lastLongitude = lastLongitude;
       this.witness = witness;
       this.helpType = helpType;
    }
   
     @Id 

    
    @Column(name="postId", nullable=false)
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="userName", nullable=false)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="latitude", nullable=false, length=122)
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", nullable=false, length=122)
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="insertDate", nullable=false, length=50)
    public String getInsertDate() {
        return this.insertDate;
    }
    
    public void setInsertDate(String insertDate) {
        this.insertDate = insertDate;
    }

    
    @Column(name="insertTime", nullable=false, length=50)
    public String getInsertTime() {
        return this.insertTime;
    }
    
    public void setInsertTime(String insertTime) {
        this.insertTime = insertTime;
    }

    
    @Column(name="LastLatitude", nullable=false, length=200)
    public String getLastLatitude() {
        return this.lastLatitude;
    }
    
    public void setLastLatitude(String lastLatitude) {
        this.lastLatitude = lastLatitude;
    }

    
    @Column(name="LastLongitude", nullable=false, length=200)
    public String getLastLongitude() {
        return this.lastLongitude;
    }
    
    public void setLastLongitude(String lastLongitude) {
        this.lastLongitude = lastLongitude;
    }

    
    @Column(name="witness", nullable=false, length=200)
    public String getWitness() {
        return this.witness;
    }
    
    public void setWitness(String witness) {
        this.witness = witness;
    }

    
    @Column(name="helpType", nullable=false)
    public String getHelpType() {
        return this.helpType;
    }
    
    public void setHelpType(String helpType) {
        this.helpType = helpType;
    }




}


