package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sosperson generated by hbm2java
 */
@Entity
@Table(name="sosperson"
    ,catalog="sos112"
)
public class Sosperson  implements java.io.Serializable {


     private String personId;
     private String postId;

    public Sosperson() {
    }

	
    public Sosperson(String personId) {
        this.personId = personId;
    }
    public Sosperson(String personId, String postId) {
       this.personId = personId;
       this.postId = postId;
    }
   
     @Id 

    
    @Column(name="personId", nullable=false)
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    
    @Column(name="postId")
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }




}


