package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sosresponse generated by hbm2java
 */
@Entity
@Table(name="sosresponse"
    ,catalog="sos112"
)
public class Sosresponse  implements java.io.Serializable {


     private String id;
     private String sosPersonId;
     private String sosPersonResponsederId;
     private String smsContent;
     private String helpType;
     private Date date;
     private String time;
     private String postId;

    public Sosresponse() {
    }

	
    public Sosresponse(String id, String sosPersonId, String sosPersonResponsederId, String smsContent, Date date, String time) {
        this.id = id;
        this.sosPersonId = sosPersonId;
        this.sosPersonResponsederId = sosPersonResponsederId;
        this.smsContent = smsContent;
        this.date = date;
        this.time = time;
    }
    public Sosresponse(String id, String sosPersonId, String sosPersonResponsederId, String smsContent, String helpType, Date date, String time, String postId) {
       this.id = id;
       this.sosPersonId = sosPersonId;
       this.sosPersonResponsederId = sosPersonResponsederId;
       this.smsContent = smsContent;
       this.helpType = helpType;
       this.date = date;
       this.time = time;
       this.postId = postId;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="sosPersonId", nullable=false)
    public String getSosPersonId() {
        return this.sosPersonId;
    }
    
    public void setSosPersonId(String sosPersonId) {
        this.sosPersonId = sosPersonId;
    }

    
    @Column(name="sosPersonResponsederId", nullable=false)
    public String getSosPersonResponsederId() {
        return this.sosPersonResponsederId;
    }
    
    public void setSosPersonResponsederId(String sosPersonResponsederId) {
        this.sosPersonResponsederId = sosPersonResponsederId;
    }

    
    @Column(name="smsContent", nullable=false)
    public String getSmsContent() {
        return this.smsContent;
    }
    
    public void setSmsContent(String smsContent) {
        this.smsContent = smsContent;
    }

    
    @Column(name="helpType")
    public String getHelpType() {
        return this.helpType;
    }
    
    public void setHelpType(String helpType) {
        this.helpType = helpType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="time", nullable=false, length=30)
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }

    
    @Column(name="PostId")
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }




}


