package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="sos112"
)
public class User  implements java.io.Serializable {


     private String mobileNumber;
     private String username;
     private String password;
     private String email;
     private String firstname;
     private String lastname;
     private Date activeSince;
     private int mobileCountryCode;

    public User() {
    }

	
    public User(String mobileNumber, String username, String email, Date activeSince, int mobileCountryCode) {
        this.mobileNumber = mobileNumber;
        this.username = username;
        this.email = email;
        this.activeSince = activeSince;
        this.mobileCountryCode = mobileCountryCode;
    }
    public User(String mobileNumber, String username, String password, String email, String firstname, String lastname, Date activeSince, int mobileCountryCode) {
       this.mobileNumber = mobileNumber;
       this.username = username;
       this.password = password;
       this.email = email;
       this.firstname = firstname;
       this.lastname = lastname;
       this.activeSince = activeSince;
       this.mobileCountryCode = mobileCountryCode;
    }
   
     @Id 

    
    @Column(name="MobileNumber", nullable=false, length=50)
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    
    @Column(name="USERNAME", nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="PASSWORD")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="EMAIL", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="FIRSTNAME")
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="LASTNAME")
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACTIVE_SINCE", nullable=false, length=19)
    public Date getActiveSince() {
        return this.activeSince;
    }
    
    public void setActiveSince(Date activeSince) {
        this.activeSince = activeSince;
    }

    
    @Column(name="Mobile_Country_Code", nullable=false)
    public int getMobileCountryCode() {
        return this.mobileCountryCode;
    }
    
    public void setMobileCountryCode(int mobileCountryCode) {
        this.mobileCountryCode = mobileCountryCode;
    }




}


