package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userdetails generated by hbm2java
 */
@Entity
@Table(name="userdetails"
    ,catalog="sos112"
)
public class Userdetails  implements java.io.Serializable {


     private String userId;
     private String gender;
     private String dateOfBirth;
     private String profession;
     private String bloodGroup;

    public Userdetails() {
    }

    public Userdetails(String userId, String gender, String dateOfBirth, String profession, String bloodGroup) {
       this.userId = userId;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.profession = profession;
       this.bloodGroup = bloodGroup;
    }
   
     @Id 

    
    @Column(name="userId", nullable=false)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="gender", nullable=false, length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="dateOfBirth", nullable=false)
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="profession", nullable=false)
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }

    
    @Column(name="bloodGroup", nullable=false)
    public String getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }




}


