package com.sos.model.sos112;
// Generated Jul 21, 2016 10:02:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VideoFile generated by hbm2java
 */
@Entity
@Table(name="video_file"
    ,catalog="sos112"
)
public class VideoFile  implements java.io.Serializable {


     private String postId;
     private String videoFileName;
     private byte[] file;
     private String filePath;
     private String date;
     private String time;
     private String fileType;

    public VideoFile() {
    }

    public VideoFile(String postId, String videoFileName, byte[] file, String filePath, String date, String time, String fileType) {
       this.postId = postId;
       this.videoFileName = videoFileName;
       this.file = file;
       this.filePath = filePath;
       this.date = date;
       this.time = time;
       this.fileType = fileType;
    }
   
     @Id 

    
    @Column(name="postId", nullable=false)
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }

    
    @Column(name="videoFileName", nullable=false)
    public String getVideoFileName() {
        return this.videoFileName;
    }
    
    public void setVideoFileName(String videoFileName) {
        this.videoFileName = videoFileName;
    }

    
    @Column(name="file", nullable=false)
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }

    
    @Column(name="filePath", nullable=false)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    
    @Column(name="date", nullable=false)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    
    @Column(name="time", nullable=false)
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }

    
    @Column(name="fileType", nullable=false)
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }




}


