package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Adminsosaction generated by hbm2java
 */
public class Adminsosaction  implements java.io.Serializable {


     private Integer id;
     private String companyId;
     private String sosPostId;
     private Date date;
     private Date time;

    public Adminsosaction() {
    }

    public Adminsosaction(String companyId, String sosPostId, Date date, Date time) {
       this.companyId = companyId;
       this.sosPostId = sosPostId;
       this.date = date;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    public String getSosPostId() {
        return this.sosPostId;
    }
    
    public void setSosPostId(String sosPostId) {
        this.sosPostId = sosPostId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


