package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * Adminsosresponse generated by hbm2java
 */
public class Adminsosresponse  implements java.io.Serializable {


     private String sosPostId;
     private String companyId;
     private String sosName;
     private String sosDateTime;
     private String compnayResonseDateTime;
     private String fiveMinute;

    public Adminsosresponse() {
    }

    public Adminsosresponse(String sosPostId, String companyId, String sosName, String sosDateTime, String compnayResonseDateTime, String fiveMinute) {
       this.sosPostId = sosPostId;
       this.companyId = companyId;
       this.sosName = sosName;
       this.sosDateTime = sosDateTime;
       this.compnayResonseDateTime = compnayResonseDateTime;
       this.fiveMinute = fiveMinute;
    }
   
    public String getSosPostId() {
        return this.sosPostId;
    }
    
    public void setSosPostId(String sosPostId) {
        this.sosPostId = sosPostId;
    }
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    public String getSosName() {
        return this.sosName;
    }
    
    public void setSosName(String sosName) {
        this.sosName = sosName;
    }
    public String getSosDateTime() {
        return this.sosDateTime;
    }
    
    public void setSosDateTime(String sosDateTime) {
        this.sosDateTime = sosDateTime;
    }
    public String getCompnayResonseDateTime() {
        return this.compnayResonseDateTime;
    }
    
    public void setCompnayResonseDateTime(String compnayResonseDateTime) {
        this.compnayResonseDateTime = compnayResonseDateTime;
    }
    public String getFiveMinute() {
        return this.fiveMinute;
    }
    
    public void setFiveMinute(String fiveMinute) {
        this.fiveMinute = fiveMinute;
    }




}


