package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * Companyaddress generated by hbm2java
 */
public class Companyaddress  implements java.io.Serializable {


     private String companyId;
     private String landMark;
     private String city;
     private String district;
     private String state;
     private String country;

    public Companyaddress() {
    }

    public Companyaddress(String companyId, String landMark, String city, String district, String state, String country) {
       this.companyId = companyId;
       this.landMark = landMark;
       this.city = city;
       this.district = district;
       this.state = state;
       this.country = country;
    }
   
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    public String getLandMark() {
        return this.landMark;
    }
    
    public void setLandMark(String landMark) {
        this.landMark = landMark;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


