package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * Countsospostuserview generated by hbm2java
 */
public class Countsospostuserview  implements java.io.Serializable {


     private String userView;
     private String timeDate;
     private String sosPostId;
     private String userId;

    public Countsospostuserview() {
    }

    public Countsospostuserview(String userView, String timeDate, String sosPostId, String userId) {
       this.userView = userView;
       this.timeDate = timeDate;
       this.sosPostId = sosPostId;
       this.userId = userId;
    }
   
    public String getUserView() {
        return this.userView;
    }
    
    public void setUserView(String userView) {
        this.userView = userView;
    }
    public String getTimeDate() {
        return this.timeDate;
    }
    
    public void setTimeDate(String timeDate) {
        this.timeDate = timeDate;
    }
    public String getSosPostId() {
        return this.sosPostId;
    }
    
    public void setSosPostId(String sosPostId) {
        this.sosPostId = sosPostId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }




}


