package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * Editimagetwo generated by hbm2java
 */
public class Editimagetwo  implements java.io.Serializable {


     private String postId;
     private byte[] file;
     private String fileUrl;

    public Editimagetwo() {
    }

    public Editimagetwo(String postId, byte[] file, String fileUrl) {
       this.postId = postId;
       this.file = file;
       this.fileUrl = fileUrl;
    }
   
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }
    public String getFileUrl() {
        return this.fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }




}


