package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * Gcmid generated by hbm2java
 */
public class Gcmid  implements java.io.Serializable {


     private String id;
     private String gcm;

    public Gcmid() {
    }

    public Gcmid(String id, String gcm) {
       this.id = id;
       this.gcm = gcm;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getGcm() {
        return this.gcm;
    }
    
    public void setGcm(String gcm) {
        this.gcm = gcm;
    }




}


