package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * Otpcode generated by hbm2java
 */
public class Otpcode  implements java.io.Serializable {


     private String userId;
     private String mobileNumber;
     private String code;

    public Otpcode() {
    }

    public Otpcode(String userId, String mobileNumber, String code) {
       this.userId = userId;
       this.mobileNumber = mobileNumber;
       this.code = code;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }




}


