package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * Sensetstatus generated by hbm2java
 */
public class Sensetstatus  implements java.io.Serializable {


     private String userId;
     private String video;
     private String sms;
     private String sosIcon;
     private String powerButton;
     private String fallSenser;
     private String shakeToPost;

    public Sensetstatus() {
    }

	
    public Sensetstatus(String userId, String video, String sms, String sosIcon, String powerButton) {
        this.userId = userId;
        this.video = video;
        this.sms = sms;
        this.sosIcon = sosIcon;
        this.powerButton = powerButton;
    }
    public Sensetstatus(String userId, String video, String sms, String sosIcon, String powerButton, String fallSenser, String shakeToPost) {
       this.userId = userId;
       this.video = video;
       this.sms = sms;
       this.sosIcon = sosIcon;
       this.powerButton = powerButton;
       this.fallSenser = fallSenser;
       this.shakeToPost = shakeToPost;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    public String getSms() {
        return this.sms;
    }
    
    public void setSms(String sms) {
        this.sms = sms;
    }
    public String getSosIcon() {
        return this.sosIcon;
    }
    
    public void setSosIcon(String sosIcon) {
        this.sosIcon = sosIcon;
    }
    public String getPowerButton() {
        return this.powerButton;
    }
    
    public void setPowerButton(String powerButton) {
        this.powerButton = powerButton;
    }
    public String getFallSenser() {
        return this.fallSenser;
    }
    
    public void setFallSenser(String fallSenser) {
        this.fallSenser = fallSenser;
    }
    public String getShakeToPost() {
        return this.shakeToPost;
    }
    
    public void setShakeToPost(String shakeToPost) {
        this.shakeToPost = shakeToPost;
    }




}


