package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * Sessionkey generated by hbm2java
 */
public class Sessionkey  implements java.io.Serializable {


     private String id;
     private String mobile;

    public Sessionkey() {
    }

    public Sessionkey(String id, String mobile) {
       this.id = id;
       this.mobile = mobile;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }




}


