package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * Sospost generated by hbm2java
 */
public class Sospost  implements java.io.Serializable {


     private String postId;
     private String userId;
     private String userName;
     private String latitude;
     private String longitude;
     private String insertDate;
     private String insertTime;
     private String lastLatitude;
     private String lastLongitude;
     private String witness;
     private String helpType;

    public Sospost() {
    }

    public Sospost(String postId, String userId, String userName, String latitude, String longitude, String insertDate, String insertTime, String lastLatitude, String lastLongitude, String witness, String helpType) {
       this.postId = postId;
       this.userId = userId;
       this.userName = userName;
       this.latitude = latitude;
       this.longitude = longitude;
       this.insertDate = insertDate;
       this.insertTime = insertTime;
       this.lastLatitude = lastLatitude;
       this.lastLongitude = lastLongitude;
       this.witness = witness;
       this.helpType = helpType;
    }
   
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getInsertDate() {
        return this.insertDate;
    }
    
    public void setInsertDate(String insertDate) {
        this.insertDate = insertDate;
    }
    public String getInsertTime() {
        return this.insertTime;
    }
    
    public void setInsertTime(String insertTime) {
        this.insertTime = insertTime;
    }
    public String getLastLatitude() {
        return this.lastLatitude;
    }
    
    public void setLastLatitude(String lastLatitude) {
        this.lastLatitude = lastLatitude;
    }
    public String getLastLongitude() {
        return this.lastLongitude;
    }
    
    public void setLastLongitude(String lastLongitude) {
        this.lastLongitude = lastLongitude;
    }
    public String getWitness() {
        return this.witness;
    }
    
    public void setWitness(String witness) {
        this.witness = witness;
    }
    public String getHelpType() {
        return this.helpType;
    }
    
    public void setHelpType(String helpType) {
        this.helpType = helpType;
    }




}


