package com.sos.admin.model.sos112;
// Generated Jul 25, 2016 7:43:30 AM by Hibernate Tools 4.3.1



/**
 * VideoFile generated by hbm2java
 */
public class VideoFile  implements java.io.Serializable {


     private String postId;
     private String videoFileName;
     private byte[] file;
     private String filePath;
     private String date;
     private String time;
     private String fileType;

    public VideoFile() {
    }

    public VideoFile(String postId, String videoFileName, byte[] file, String filePath, String date, String time, String fileType) {
       this.postId = postId;
       this.videoFileName = videoFileName;
       this.file = file;
       this.filePath = filePath;
       this.date = date;
       this.time = time;
       this.fileType = fileType;
    }
   
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }
    public String getVideoFileName() {
        return this.videoFileName;
    }
    
    public void setVideoFileName(String videoFileName) {
        this.videoFileName = videoFileName;
    }
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }




}


