package com.sos.model.sosadmin;
// Generated Jul 21, 2016 7:01:08 AM by Hibernate Tools 4.3.1



/**
 * Activeuser generated by hbm2java
 */
public class Activeuser  implements java.io.Serializable {


     private String userId;
     private String loginTime;
     private Double latitute;
     private double longtitue;

    public Activeuser() {
    }

	
    public Activeuser(String userId, String loginTime, double longtitue) {
        this.userId = userId;
        this.loginTime = loginTime;
        this.longtitue = longtitue;
    }
    public Activeuser(String userId, String loginTime, Double latitute, double longtitue) {
       this.userId = userId;
       this.loginTime = loginTime;
       this.latitute = latitute;
       this.longtitue = longtitue;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime;
    }
    public Double getLatitute() {
        return this.latitute;
    }
    
    public void setLatitute(Double latitute) {
        this.latitute = latitute;
    }
    public double getLongtitue() {
        return this.longtitue;
    }
    
    public void setLongtitue(double longtitue) {
        this.longtitue = longtitue;
    }




}


