package com.sos.model.sosadmin;
// Generated Jul 21, 2016 7:01:08 AM by Hibernate Tools 4.3.1



/**
 * Audiorecords generated by hbm2java
 */
public class Audiorecords  implements java.io.Serializable {


     private String timeDate;
     private String postId;
     private byte[] audioFile;
     private String fileUrl;

    public Audiorecords() {
    }

    public Audiorecords(String timeDate, String postId, byte[] audioFile, String fileUrl) {
       this.timeDate = timeDate;
       this.postId = postId;
       this.audioFile = audioFile;
       this.fileUrl = fileUrl;
    }
   
    public String getTimeDate() {
        return this.timeDate;
    }
    
    public void setTimeDate(String timeDate) {
        this.timeDate = timeDate;
    }
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }
    public byte[] getAudioFile() {
        return this.audioFile;
    }
    
    public void setAudioFile(byte[] audioFile) {
        this.audioFile = audioFile;
    }
    public String getFileUrl() {
        return this.fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }




}


