package com.sos.model.sosadmin;
// Generated Jul 21, 2016 7:01:08 AM by Hibernate Tools 4.3.1



/**
 * GeolocationConvertAddress generated by hbm2java
 */
public class GeolocationConvertAddress  implements java.io.Serializable {


     private String userId;
     private String addressOne;
     private String date;
     private String time;

    public GeolocationConvertAddress() {
    }

    public GeolocationConvertAddress(String userId, String addressOne, String date, String time) {
       this.userId = userId;
       this.addressOne = addressOne;
       this.date = date;
       this.time = time;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getAddressOne() {
        return this.addressOne;
    }
    
    public void setAddressOne(String addressOne) {
        this.addressOne = addressOne;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }




}


