package com.sos.model.sosadmin;
// Generated Jul 21, 2016 7:01:08 AM by Hibernate Tools 4.3.1



/**
 * GroupHasUser generated by hbm2java
 */
public class GroupHasUser  implements java.io.Serializable {


     private String id;
     private String groupid;
     private String userid;

    public GroupHasUser() {
    }

	
    public GroupHasUser(String id) {
        this.id = id;
    }
    public GroupHasUser(String id, String groupid, String userid) {
       this.id = id;
       this.groupid = groupid;
       this.userid = userid;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }




}


