package com.sos.model.sosadmin;
// Generated Jul 21, 2016 7:01:08 AM by Hibernate Tools 4.3.1



/**
 * Profilepicture generated by hbm2java
 */
public class Profilepicture  implements java.io.Serializable {


     private String userId;
     private byte[] picture;
     private String fileUrl;

    public Profilepicture() {
    }

    public Profilepicture(String userId, byte[] picture, String fileUrl) {
       this.userId = userId;
       this.picture = picture;
       this.fileUrl = fileUrl;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }
    public String getFileUrl() {
        return this.fileUrl;
    }
    
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }




}


