package com.sos.model.sosadmin;
// Generated Jul 21, 2016 7:01:08 AM by Hibernate Tools 4.3.1



/**
 * Sospostfinal generated by hbm2java
 */
public class Sospostfinal  implements java.io.Serializable {


     private String id;
     private String postId;
     private String postTitle;
     private String helpType;
     private String dateTime;

    public Sospostfinal() {
    }

    public Sospostfinal(String id, String postId, String postTitle, String helpType, String dateTime) {
       this.id = id;
       this.postId = postId;
       this.postTitle = postTitle;
       this.helpType = helpType;
       this.dateTime = dateTime;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }
    public String getPostTitle() {
        return this.postTitle;
    }
    
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }
    public String getHelpType() {
        return this.helpType;
    }
    
    public void setHelpType(String helpType) {
        this.helpType = helpType;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }




}


