package com.sos.model.sosadmin;
// Generated Jul 21, 2016 7:01:08 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sosresponse generated by hbm2java
 */
public class Sosresponse  implements java.io.Serializable {


     private String id;
     private String sosPersonId;
     private String sosPersonResponsederId;
     private String smsContent;
     private String helpType;
     private Date date;
     private String time;
     private String postId;

    public Sosresponse() {
    }

	
    public Sosresponse(String id, String sosPersonId, String sosPersonResponsederId, String smsContent, Date date, String time) {
        this.id = id;
        this.sosPersonId = sosPersonId;
        this.sosPersonResponsederId = sosPersonResponsederId;
        this.smsContent = smsContent;
        this.date = date;
        this.time = time;
    }
    public Sosresponse(String id, String sosPersonId, String sosPersonResponsederId, String smsContent, String helpType, Date date, String time, String postId) {
       this.id = id;
       this.sosPersonId = sosPersonId;
       this.sosPersonResponsederId = sosPersonResponsederId;
       this.smsContent = smsContent;
       this.helpType = helpType;
       this.date = date;
       this.time = time;
       this.postId = postId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getSosPersonId() {
        return this.sosPersonId;
    }
    
    public void setSosPersonId(String sosPersonId) {
        this.sosPersonId = sosPersonId;
    }
    public String getSosPersonResponsederId() {
        return this.sosPersonResponsederId;
    }
    
    public void setSosPersonResponsederId(String sosPersonResponsederId) {
        this.sosPersonResponsederId = sosPersonResponsederId;
    }
    public String getSmsContent() {
        return this.smsContent;
    }
    
    public void setSmsContent(String smsContent) {
        this.smsContent = smsContent;
    }
    public String getHelpType() {
        return this.helpType;
    }
    
    public void setHelpType(String helpType) {
        this.helpType = helpType;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getPostId() {
        return this.postId;
    }
    
    public void setPostId(String postId) {
        this.postId = postId;
    }




}


